version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: edudig-backend
    ports:
      - "8053:8053"
  frontend:
    build:
      context: ./edudig-react/
    container_name: edudig-frontend
    ports:
      - "3000:80"
    environment:
      - "baseURL=http://localhost:8053/"
